# Generated by Django 4.2.2 on 2023-06-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='published_date',
        ),
    ]
