# Generated by Django 4.2.2 on 2023-07-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiration_date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='published_date',
            field=models.CharField(max_length=15),
        ),
    ]
