# Generated by Django 4.2.2 on 2023-06-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
